In [5]:
import tensorflow.keras as tf 
import numpy as np 
import tensorflow as tf1


In [48]:
numpy_array = np.arange(12)
tensor_3d = tf1.Variable(numpy_array)
tensor_3d = tf1.reshape(tensor_3d, (1, 2, 2, 3))
tensor_3d = tf1.cast(tensor_3d, 'float32')

# **Difference Between Conv2DTranspose and Upsampling ?**

Both are used for upsampling the matrix, both uses a different method to do a upsampling

**Conv2DTranspose :**  
Normal Convolution operation beteee the feature map and the kernel but in the different way. It takes more time for the computation. It is used in the       **UNET**for Image Segmentation

**UpSampling :** 

It just pick the values from the nereast pixel and create a new upsampled matrix. It advantage is that it computation is cheaper. It is used in the **AutoEncoders** for Reduction of Dimensionality

In [49]:
tf.layers.Conv2DTranspose(kernel_size = (3, 3), filters = 3, padding = 'same', strides = (2, 2))(tensor_3d)

<tf.Tensor: shape=(1, 4, 4, 3), dtype=float32, numpy=
array([[[[ 0.8626628 ,  0.48634994, -0.5547034 ],
         [ 0.5048387 ,  0.3367303 , -0.51814616],
         [ 3.7469888 , -0.10757887, -1.0595675 ],
         [ 1.7484478 ,  1.0347728 , -0.47677183]],

        [[-0.63172096,  0.6909574 ,  0.8221617 ],
         [ 0.27613145, -0.07098261, -0.07932958],
         [-1.4420178 ,  1.8672435 ,  1.0048254 ],
         [ 1.7169793 ,  0.2495481 , -0.4736556 ]],

        [[ 4.9307346 , -0.7583957 , -1.7704493 ],
         [ 3.180777  ,  1.3953294 , -0.55090976],
         [ 9.218759  , -2.6948667 , -0.64025116],
         [ 5.207037  ,  0.94250476, -1.4328058 ]],

        [[-3.1487575 ,  3.4718838 ,  2.1066236 ],
         [ 3.1578271 ,  0.57007873, -0.8679817 ],
         [-1.1023927 ,  4.5587664 ,  0.93899596],
         [ 4.598675  ,  0.8906095 , -1.2623076 ]]]], dtype=float32)>

Reshaped the 2 * 2 * 3 image into 4 * 4 * 3, basically upsampled using the Conv2dTranspose, this is used in unet for Image segmentation
 

In [54]:
tf.layers.UpSampling2D(size = (2, 2))(tensor_3d)

<tf.Tensor: shape=(1, 4, 4, 3), dtype=float32, numpy=
array([[[[ 0.,  1.,  2.],
         [ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 3.,  4.,  5.]],

        [[ 0.,  1.,  2.],
         [ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [ 9., 10., 11.]],

        [[ 6.,  7.,  8.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [ 9., 10., 11.]]]], dtype=float32)>

Reshaped the 2 * 2 * 3 image into 4 * 4 * 3, basically upsampled using the UpSampling, this is used in unet for Image segmentation
 